### ISSUE TITLE
reference block is not updated

### ISSUE THREAD

**Issue by randomwangran** [Kinneyzhang/roam-block#2]
I have a set up like this:

    (require 'roam-block)
    
    (setq roam-block-home '("~/roam-block/")
          roam-block-ref-highlight t)
    
    (roam-block-mode 1)
    
    (define-key roam-block-mode-map (kbd "C-c b c") #'roam-block-ref-store)
    (define-key roam-block-mode-map (kbd "C-c b i") #'roam-block-ref-insert)
    (define-key roam-block-mode-map (kbd "C-c b e") #'roam-block-ref-edit)
    (define-key roam-block-mode-map (kbd "C-c b d") #'roam-block-ref-delete)

I marked a region, and executed `roam-block-ref-store`. I was promoted
by a message: `(roam-block) The block refs are stored.`

Then I move the marker somewhere else and execute
`roam-block-ref-insert`. I find the content is being inserted to the
point. However, I think the content is just being yanked to the point,
not a reference block.

I then go back to the source, edited the source, and save the buffer.
I find that the reference block is not updated.

![demo-show-block](https://user-images.githubusercontent.com/8197831/102502912-2e659200-404d-11eb-84cb-c408e42c895e.gif)

**Comment by Kinneyzhang** [comment]
Check the following procedures：

1. Make sure the file you edit is in roam-block-home directory. Eval roam-block-work-on function to check it.

2. Call command 'describe-text-properties' on the source block  to check if there's a uuid property.

3. roam-block-ref-insert should insert a uuid ref at point and the uuid ref is displayed as the source block content. Close roam-block-mode to see if it's inserted correctly.

4. If none of condition is satisfied, something is wrong with database maybe.

**Comment by randomwangran** [comment]
> Make sure the file you edit is in roam-block-home directory.

This solve my issue. And also #3.

Thanks for writing this package. Really appreciate it.
