### ISSUE TITLE
What is an active region?

### ISSUE THREAD

**Issue by randomwangran** [Kinneyzhang/roam-block#3]
I've watched your demonstration video. I find that I could not repeat
what you do in the video. In the video (0:02), you move the marker to a
paragraph then execute the function `roam-block-ref-store`.

I could not repeat it. On my side, if I execute
`roam-block-ref-store` in a paragraph, I was promoted by this message:
`user-error: (roam-block) No valid block here!`

However, if I mark the paragraph and then execute
`roam-block-ref-store`, I was promoted by a message: 
`(roam-block) The block refs are stored.`

**Comment by Kinneyzhang** [comment]
An active region is used to store multiple blocks' refs.

**Comment by randomwangran** [comment]
Thanks for your suggestion.

I find if the setting is correct:
> Make sure the file you edit is in roam-block-home directory.

  It is not required to mark the region to store the block reference.
