### ISSUE TITLE
Render Org-link

### ISSUE THREAD

**Issue by randomwangran** [Kinneyzhang/roam-block#5]
I find that the link in the embed block is being displayed as the raw text.

It would be nicer to render them as a click-able Org-mode link.

![image](https://user-images.githubusercontent.com/8197831/102521836-68419300-4063-11eb-8fe3-8c4205870bc1.png)

**Comment by Kinneyzhang** [comment]
Thanks for your feedback. I will render the org-link as the origin format, but cannot make it clickable because it's actually a block ref, not a block embed.

**Comment by Kinneyzhang** [comment]
Have fixed this issue, pull the latest commit to have a try.

**Comment by randomwangran** [comment]
I am on e15e18c3eba673eab63c033fce22d2669a087351.

I find the link is being correctly rendered.

But the issue is that I could not click the link. The following gif
shows the result. I could not use mouse or marker to click the link.

Before, I test with `emacs -q`, I just want to confirm with you.

![demo-show-link](https://user-images.githubusercontent.com/8197831/102668122-26931400-4159-11eb-83dc-4f71af4e019b.gif)

**Comment by Kinneyzhang** [comment]
Yes, you cannot click the link because there's actually no link there.

> Thanks for your feedback. I will render the org-link as the origin format, but cannot make it clickable because it's actually a block ref, not a block embed.

As I have mentioned above, the real text of a block ref is "((UUID))" and the content displayed is just a display property of it. That's what 'block ref' means. If you want to click a org link, you should use block embed which is what I am working on now.

**Comment by randomwangran** [comment]
Sorry about that. I miss your comment and I misunderstood the mean of "block ref" and "block embed".

There is a package: [Org-transclusion](https://github.com/nobiot/org-transclusion) targeting on similar feature. Noboru has been put a lot of effort to make it useful. I personally use it everyday. In <https://github.com/bastibe/annotate.el/issues/91#issue-769160655>, the first figure I've shown, it's a minor mode being turn on. The content is actually an overlay, but the Org-mode link in there is click-able.

Noboru gave me suggestions in <https://github.com/bastibe/annotate.el/issues/91#issuecomment-747921667>. I am also an elisp beginner, but I will try to understand how the link works in the overlay.

**Comment by Kinneyzhang** [comment]
> it's a minor mode being turn on. The content is actually an overlay, but the Org-mode link in there is click-able.

If related to overlay, it should implement the clickable org link easier since 'overlay' is more flexible than text property. But, the reason I switch from overlay to text property is that text property has a better performance than overlay when the number of block ref is a huge in a file.
