### ISSUE TITLE
Issue with cpp file

### ISSUE THREAD

**Issue by randomwangran** [Kinneyzhang/roam-block#6]
If I have a file within `roam-block-home` directory:

    class fileMonitor
    {
    
    public:
    
        // Public data types
    
            //- Enumeration defining the file state.
            enum fileState
            {
                UNMODIFIED = 0,
                MODIFIED = 1,
                DELETED = 2
            };
    
      ...
    }

I place the mark like this:

![image](https://user-images.githubusercontent.com/8197831/102522852-cae75e80-4064-11eb-857b-37f8472c0f74.png)

And I execute the `roam-block-ref-store`, I get this message:

`user-error: (roam-block) No valid block here!`

I was wondering how to define the block besides the Org-mode files.

**Comment by Kinneyzhang** [comment]
Roam block now only support block ref in org-mode files. Actually, I am still thinking of whether to support program language files since it's a rare case to reference a code block in other files. It's more meaningful to support the format like org, md, txt and so on.

**Comment by randomwangran** [comment]
Yes, you are right. After a good sleep, I am thinking what "things"
need to be transcluded (or block-reference).

I think the content being referred should be something constantly
updated. That's why we need to treat the atomic note as the content of
pointer (or the content pointer pointing to). Other place need to
access the content, a user just need to add a new pointer pointing to
the address of the atomic note. (sorry for using a bad metaphor)

The source code that I take note is usually an archive. It's not going to
be changed, so there is no motivation for updates.

Since you already done the Org-mode link render in <https://github.com/Kinneyzhang/roam-block/commit/495350c1af79527a929d6b300e27e75f777d0adf>, 
I will have a try on that and not use block reference to a source code, 
so I close this issue.
