### ISSUE TITLE
Effective way to search the database

### ISSUE THREAD

**Issue by randomwangran** [Kinneyzhang/roam-block#7]
Currently, user need to go to the source content, then execute
`roam-block-store-link` go back to the target file and execute
`roam-block-ref-insert`.

I image this is the correct way to do it.

It would be nicer to query the database, locate the target sources,
then insert them to the current working file at point.

**Comment by Kinneyzhang** [comment]
This is definitely a new feature in plan. I will implement this as what roam research has implemented. It means, in "(())", when you continue to input, it will prompt completion candidates to match your input string.

**Comment by randomwangran** [comment]
I am glad you will try to improve this feature. I will let the issue
open, but feel free to close it as you wish.

As I test roam-block more, I am also thinking how you will apply the
searching strategy, so I just write down some of my thoughts in https://github.com/Kinneyzhang/roam-block/issues/9.

Don't feel any pressure on my issue. I am not asking you to do anything.
You already done the good work. Keep good work and have fun.
