### ISSUE TITLE
Question on UUID format

### ISSUE THREAD

**Issue by randomwangran** [Kinneyzhang/roam-block#8]
I've noticed that UUID was reformatted by this function:

  https://github.com/Kinneyzhang/roam-block/blob/f9e6708a3a64419c6a46ec46e315a2134583c69d/roam-block-util.el#L46-L48
  
  I was wondering why this is necessary.

  If the UUID is kept in the original format, it would be possible to
  be compatible with other softwares, e.g., logseq's block reference.

**Comment by Kinneyzhang** [comment]
My idea is to keep uuid as simple as possible. 

> If the UUID is kept in the original format, it would be possible to
be compatible with other softwares, e.g., logseq's block reference.

Ok, considering of this, I will change the uuid format to the original one.

**Comment by Kinneyzhang** [comment]
Use ```roam-block-db-clear``` to clear caches in database and then reopen org file, all uuid properties will change. Need to insert block refs manually again.
