### ISSUE TITLE
Roam-block searching strategy

### ISSUE THREAD

**Issue by randomwangran** [Kinneyzhang/roam-block#9]
Currently, the block reference is extremely flexible.

Taking the following headline content as an example, I will try to
understand the possible search strategy.

```
* a headline
  :PROPERTIES:
  :ID:       UUID
  :END:
Paragraph A. Something.

Paragraph B. Something.

Paragraph C. Something.
```

Logseq treats ((UUID)) as an index to the example headline above. Any
place referring this UUID by block-embed, will transclude the content
of this headline. If this headline has sub-headline, it will also
include them.

`Roam-block` has finner block. User can store `Paragraph A. Something.`,
 `Paragraph B. Something.`, and `Paragraph C. Something.` as
three blocks even they are in the same headline.

This is more flexible but it might introduce some issues to search the
content. If the searching strategy is based on the content of the
block. For example, if a user wants to search a term "Paragraph B",
the searching engine will look for "Paragraph B" in the database. This
is not a problem if the database is small.

The problem is that, it lacks a "title". I believe that this the most
commonly way to search for a slip card content in many Roam-like
software.

Don't feel any pressure on my issue. I am not asking you to anything.
You already done the good work. Keep good work and have fun.

**Comment by Kinneyzhang** [comment]
> The problem is that, it lacks a "title". I believe that this the most
commonly way to search for a slip card content in many Roam-like
software.

I cannot understand what it means. If a user choose to insert a block ref by querying the database, it have to search all blocks' content for a proper match. But, what's to do with title or headline?

**Comment by Kinneyzhang** [comment]
Please continue this discussion in https://github.com/Kinneyzhang/roam-block/discussions/11#discussion-77107.
